version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
  
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=is442
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mydb
    volumes:
      - oopsies-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    

  
volumes:
  oopsies-data:
